version: '3.4'
  # use id: 2587 in the dashboards import section
networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:1.8
    container_name: benchmark-influxdb
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:10.2.0
    container_name: benchmark-grafana
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  k6:
    image: grafana/k6:0.47.0
    container_name: benchmark-k6
    networks:
      - k6
    ports:
      - "6565:6565"
    command: run --out influxdb=http://influxdb:8086 /scripts/localhost.js
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts
