apiVersion: 1

deleteDatasources:
  - name: k6influxdb
    orgId: 1

datasources:
- name: k6influxdb
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  password:
  user:
  database: 
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
     dbName: k6
  readOnly: false
